# Generated by Django 4.2 on 2023-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analysis', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('credit_rating_borrower', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=256)),
                ('principal', models.CharField(max_length=256)),
                ('type_of_interest_rate', models.CharField(max_length=256)),
                ('base_rate', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
