# Generated by Django 4.2 on 2023-05-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_benchmark_delete_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPfinsTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=256)),
                ('principal', models.CharField(max_length=256)),
                ('type_of_interest_rate', models.CharField(max_length=256)),
                ('base_rate', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
